### ISSUE TITLE
Add support and security disclosure links on page

### ISSUE THREAD

**Issue by imaginaryusername** [bitcoin-cash-node/bchnode-web#138]
Can probably be shoved in "contacts" leaving room for other kinds of contact too - or even just a link to the disclosure policy will do.

**Comment by merc1er** [comment]
Could you share these links here?

**Comment by imaginaryusername** [comment]
support@bitcoincashnode.org and security@bitcoincashnode.org

**Comment by merc1er** [comment]
Done ✅
