### ISSUE TITLE
Add a "getting started" page

### ISSUE THREAD

**Issue by merc1er** [bitcoin-cash-node/bchnode-web#56]
What do you think about a "getting started" page listing useful commands to do after a fresh install of BCHN?

For example, how to start/stop `bitcoind`, how to check the initial block download, change the data directory to an external drive etc...

[bitcoin.org/en/full-node](https://bitcoin.org/en/full-node) is a great resource in my opinion and I had to use it a number of times as I couldn't find such documentation on any of the BCH full nodes.

**Comment by emergent-reasons** [comment]
Love it! I think it just needs to have a bit of vision guiding the content considering the main target audiences of BCHN.

**Comment by merc1er** [comment]
This should be in the docs.bitcoincashnode.org site.
